/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.2.0
 *
 * Project: 'Blinky.Debug+NUCLEO-G0B1RE' 
 * Target:  'Debug+NUCLEO-G0B1RE' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Keil::Device:STM32Cube HAL:Common@1.4.5 */
#define USE_HAL_DRIVER


#endif /* PRE_INCLUDE_GLOBAL_H */
