/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.2.0
 *
 * Project: 'Blinky.Debug+NUCLEO-G0B1RE' 
 * Target:  'Debug+NUCLEO-G0B1RE' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32g0xx.h"

/* ARM::CMSIS-View:Event Recorder&DAP@1.5.3 */
#define RTE_CMSIS_View_EventRecorder
        #define RTE_CMSIS_View_EventRecorder_DAP
/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.8.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
        #define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
        #define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* Keil::CMSIS Driver:VIO:Board&NUCLEO-G0B1RE@2.0.0 */
#define RTE_VIO_BOARD
        #define RTE_VIO_NUCLEO_G0B1RE
/* Keil::Device:STM32Cube Framework:STM32CubeMX@1.1.0 */
#define RTE_DEVICE_FRAMEWORK_CUBE_MX
/* Keil::Device:STM32Cube HAL:Common@1.4.5 */
#define RTE_DEVICE_HAL_COMMON
/* Keil::Device:STM32Cube HAL:Cortex@1.4.5 */
#define RTE_DEVICE_HAL_CORTEX
/* Keil::Device:STM32Cube HAL:DMA@1.4.5 */
#define RTE_DEVICE_HAL_DMA
/* Keil::Device:STM32Cube HAL:GPIO@1.4.5 */
#define RTE_DEVICE_HAL_GPIO
/* Keil::Device:STM32Cube HAL:PWR@1.4.5 */
#define RTE_DEVICE_HAL_PWR
/* Keil::Device:STM32Cube HAL:RCC@1.4.5 */
#define RTE_DEVICE_HAL_RCC
/* Keil::Device:STM32Cube HAL:UART@1.4.5 */
#define RTE_DEVICE_HAL_UART
/* Keil::Device:Startup@1.6.0 */
#define RTE_DEVICE_STARTUP_STM32G0XX    /* Device Startup for STM32G0 */


#endif /* RTE_COMPONENTS_H */
